# Generated by Django 3.2 on 2021-05-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210515_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
