# Generated by Django 3.2 on 2021-05-23 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
