# Generated by Django 3.2 on 2021-05-25 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='students',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
